### ISSUE TITLE
Last update timestamp

### ISSUE THREAD

**Issue by pabloab** [biblibre/hea-app#17]
There are some libraries that maybe send their info long ago and they don't even exist. Is possible for people to enable sysprefs mistakenly. That's way we have 12 libraries with "library.example.org" as their URL. Maybe they fix it but the damage was done. I understand is a difficult situation but at least a timestamp of last update could reduce the problem.

**Comment by clrh** [comment]
Hi @pabloab thanks for your feedback. Please use https://gitlab.com/koha-community/hea-app/ repository. We have to close this one :)

Thanks!
