### ISSUE TITLE
Wrong libraries filters

### ISSUE THREAD

**Issue by pabloab** [biblibre/hea-app#18]
- Where it say "See all libraries" should say "see all Koha deployments"
- Where it say "See by country" should say "See Koha branches by country"

I don't know what it say on "See on a map" since it doesn't work at all.

**Comment by clrh** [comment]
Hi @pabloab thanks for your feedback. Please use https://gitlab.com/koha-community/hea-app/ repository. We have to close this one :)

Thanks!
