### ISSUE TITLE
See by country just list branches names

### ISSUE THREAD

**Issue by pabloab** [biblibre/hea-app#19]
See by country just list {country} > {branchName}. That led to things like:

- 3 "union"
- 5 "prueba" (_test_ in Spanish)- 
- 10 "ไม่กำหนด" ("not determined" in Thai)

People use {branchName} in context, things like "Central library" is enough.

HEA could list in three levels: {country} > UsageStatsLibraryName > {branchName}

**Comment by clrh** [comment]
Hi @pabloab thanks for your feedback. Please use https://gitlab.com/koha-community/hea-app/ repository. We have to close this one :)

Thanks!
